services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ts-monorepo-boilerplate
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ts-monorepo-boilerplate_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  ts-monorepo-boilerplate_data:
    name: ts-monorepo-boilerplate_data

networks:
  app-network:
    driver: bridge
